# Generated by Django 5.0.1 on 2024-02-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='updated_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
