# Generated by Django 5.0.1 on 2024-02-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0002_alter_expenserequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
    ]
