# Generated by Django 5.0.1 on 2024-02-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0004_alter_expenserequest_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='description',
        ),
    ]
